from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoHilActuatorControls:
    """
    ROS message: hako_mavlink_msgs/HakoHilActuatorControls
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.time_usec: int = 0
        self.controls: List[float] = []
        self.mode: int = 0
        self.flags: int = 0

    def __str__(self):
        return f"HakoHilActuatorControls(" + ", ".join([
            f"time_usec={self.time_usec}"
            f"controls={self.controls}"
            f"mode={self.mode}"
            f"flags={self.flags}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
