from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoSystemTime:
    """
    ROS message: hako_mavlink_msgs/HakoSystemTime
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.time_unix_usec: int = 0
        self.time_boot_ms: int = 0

    def __str__(self):
        return f"HakoSystemTime(" + ", ".join([
            f"time_unix_usec={self.time_unix_usec}"
            f"time_boot_ms={self.time_boot_ms}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
