from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoGLOBAL_POSITION_INT:
    """
    ROS message: hako_mavlink_msgs/HakoGLOBAL_POSITION_INT
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.time_boot_ms: int = 0
        self.lat: int = 0
        self.lon: int = 0
        self.alt: int = 0
        self.relative_alt: int = 0
        self.vx: int = 0
        self.vy: int = 0
        self.vz: int = 0
        self.hdg: int = 0

    def __str__(self):
        return f"HakoGLOBAL_POSITION_INT(" + ", ".join([
            f"time_boot_ms={self.time_boot_ms}"
            f"lat={self.lat}"
            f"lon={self.lon}"
            f"alt={self.alt}"
            f"relative_alt={self.relative_alt}"
            f"vx={self.vx}"
            f"vy={self.vy}"
            f"vz={self.vz}"
            f"hdg={self.hdg}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
