from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoHeartbeat:
    """
    ROS message: hako_mavlink_msgs/HakoHeartbeat
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.type: int = 0
        self.autopilot: int = 0
        self.base_mode: int = 0
        self.custom_mode: int = 0
        self.system_status: int = 0
        self.mavlink_version: int = 0

    def __str__(self):
        return f"HakoHeartbeat(" + ", ".join([
            f"type={self.type}"
            f"autopilot={self.autopilot}"
            f"base_mode={self.base_mode}"
            f"custom_mode={self.custom_mode}"
            f"system_status={self.system_status}"
            f"mavlink_version={self.mavlink_version}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
