from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoHilSensor:
    """
    ROS message: hako_mavlink_msgs/HakoHilSensor
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.time_usec: int = 0
        self.xacc: float = 0.0
        self.yacc: float = 0.0
        self.zacc: float = 0.0
        self.xgyro: float = 0.0
        self.ygyro: float = 0.0
        self.zgyro: float = 0.0
        self.xmag: float = 0.0
        self.ymag: float = 0.0
        self.zmag: float = 0.0
        self.abs_pressure: float = 0.0
        self.diff_pressure: float = 0.0
        self.pressure_alt: float = 0.0
        self.temperature: float = 0.0
        self.fields_updated: int = 0
        self.id: int = 0

    def __str__(self):
        return f"HakoHilSensor(" + ", ".join([
            f"time_usec={self.time_usec}"
            f"xacc={self.xacc}"
            f"yacc={self.yacc}"
            f"zacc={self.zacc}"
            f"xgyro={self.xgyro}"
            f"ygyro={self.ygyro}"
            f"zgyro={self.zgyro}"
            f"xmag={self.xmag}"
            f"ymag={self.ymag}"
            f"zmag={self.zmag}"
            f"abs_pressure={self.abs_pressure}"
            f"diff_pressure={self.diff_pressure}"
            f"pressure_alt={self.pressure_alt}"
            f"temperature={self.temperature}"
            f"fields_updated={self.fields_updated}"
            f"id={self.id}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
