from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoSystemTime:
    """
    ROS message: hako_mavlink_msgs/HakoSystemTime
    Generated by hakoniwa-ros2pdu.
    """

    time_unix_usec: int
    time_boot_ms: int

    def __init__(self):
        self.time_unix_usec = 0
        self.time_boot_ms = 0

    def __str__(self):
        return f"HakoSystemTime(" + ", ".join([
            f"time_unix_usec={self.time_unix_usec}"
            f"time_boot_ms={self.time_boot_ms}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'time_unix_usec'
        field_val = self.time_unix_usec
        if isinstance(field_val, bytearray):
            d['time_unix_usec'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['time_unix_usec'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['time_unix_usec'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['time_unix_usec'] = field_val
        # handle field 'time_boot_ms'
        field_val = self.time_boot_ms
        if isinstance(field_val, bytearray):
            d['time_boot_ms'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['time_boot_ms'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['time_boot_ms'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['time_boot_ms'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'time_unix_usec'
        if 'time_unix_usec' in d:
            field_type = cls.__annotations__.get('time_unix_usec')
            value = d['time_unix_usec']
            
            if field_type is bytearray:
                obj.time_unix_usec = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.time_unix_usec = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.time_unix_usec = value
            elif hasattr(field_type, 'from_dict'):
                obj.time_unix_usec = field_type.from_dict(value)
            else:
                obj.time_unix_usec = value
        # handle field 'time_boot_ms'
        if 'time_boot_ms' in d:
            field_type = cls.__annotations__.get('time_boot_ms')
            value = d['time_boot_ms']
            
            if field_type is bytearray:
                obj.time_boot_ms = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.time_boot_ms = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.time_boot_ms = value
            elif hasattr(field_type, 'from_dict'):
                obj.time_boot_ms = field_type.from_dict(value)
            else:
                obj.time_boot_ms = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
