from typing import List
{% for item in container.py_imports %}
from ..{{ item.dep_pkg }}.{{ item.file }} import {{ item.class_name }}
{% endfor %}

class {{ container.class_name }}:
    """
    ROS message: {{ container.pkg_name }}/{{ container.msg_type_name }}
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
{%- for field in container.json_data["fields"] %}
        self.{{ field.name }}: {{ container.get_python_type_hint(field.type) }} = {{ container.get_python_default_value(field.type) }}
{%- endfor %}

    def __str__(self):
        return f"{{ container.class_name }}(" + ", ".join([
{%- for field in container.json_data["fields"] %}
            f"{{ field.name }}={self.{{ field.name }}}"
{%- endfor %}
        ]) + ")"

    def __repr__(self):
        return self.__str__()
