

/**
 * ROS message: builtin_interfaces/Time
 * Generated by hakoniwa-ros2pdu.
 */
export class Time {
/** @type { number } */
    sec;
/** @type { number } */
    nanosec;


    constructor() {
        this.sec = 0;
        this.nanosec = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'sec'
            const field_val = this.sec;
            if (typeof field_val?.toDict === 'function') {
                d['sec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['sec'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['sec'] = field_val;
            }
        }
        {
            // handle field 'nanosec'
            const field_val = this.nanosec;
            if (typeof field_val?.toDict === 'function') {
                d['nanosec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['nanosec'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['nanosec'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { Time }
     */
    static fromDict(d) {
        const obj = new Time();
        if (d.hasOwnProperty('sec')) {
            obj.sec = d.sec;
        }
        if (d.hasOwnProperty('nanosec')) {
            obj.nanosec = d.nanosec;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { Time }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
