import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { PointField } from '../sensor_msgs/pdu_jstype_PointField.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';


/**
 * ROS message: sensor_msgs/PointCloud2
 * Generated by hakoniwa-ros2pdu.
 */
export class PointCloud2 {
/** @type { Header } */
    header;
/** @type { number } */
    height;
/** @type { number } */
    width;
/** @type { Array<PointField> } */
    fields;
/** @type { boolean } */
    is_bigendian;
/** @type { number } */
    point_step;
/** @type { number } */
    row_step;
/** @type { Array<number> } */
    data;
/** @type { boolean } */
    is_dense;


    constructor() {
        this.header = null;
        this.height = 0;
        this.width = 0;
        this.fields = [];
        this.is_bigendian = false;
        this.point_step = 0;
        this.row_step = 0;
        this.data = [];
        this.is_dense = false;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'height'
            const field_val = this.height;
            if (typeof field_val?.toDict === 'function') {
                d['height'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['height'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['height'] = field_val;
            }
        }
        {
            // handle field 'width'
            const field_val = this.width;
            if (typeof field_val?.toDict === 'function') {
                d['width'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['width'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['width'] = field_val;
            }
        }
        {
            // handle field 'fields'
            const field_val = this.fields;
            if (typeof field_val?.toDict === 'function') {
                d['fields'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['fields'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['fields'] = field_val;
            }
        }
        {
            // handle field 'is_bigendian'
            const field_val = this.is_bigendian;
            if (typeof field_val?.toDict === 'function') {
                d['is_bigendian'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['is_bigendian'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['is_bigendian'] = field_val;
            }
        }
        {
            // handle field 'point_step'
            const field_val = this.point_step;
            if (typeof field_val?.toDict === 'function') {
                d['point_step'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['point_step'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['point_step'] = field_val;
            }
        }
        {
            // handle field 'row_step'
            const field_val = this.row_step;
            if (typeof field_val?.toDict === 'function') {
                d['row_step'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['row_step'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['row_step'] = field_val;
            }
        }
        {
            // handle field 'data'
            const field_val = this.data;
            if (typeof field_val?.toDict === 'function') {
                d['data'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['data'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['data'] = field_val;
            }
        }
        {
            // handle field 'is_dense'
            const field_val = this.is_dense;
            if (typeof field_val?.toDict === 'function') {
                d['is_dense'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['is_dense'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['is_dense'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { PointCloud2 }
     */
    static fromDict(d) {
        const obj = new PointCloud2();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('height')) {
            obj.height = d.height;
        }
        if (d.hasOwnProperty('width')) {
            obj.width = d.width;
        }
        if (d.hasOwnProperty('fields')) {
            const item_class = PointField;
            if (Array.isArray(d.fields)) {
                obj.fields = d.fields.map(item => item_class.fromDict(item));
            }
        }
        if (d.hasOwnProperty('is_bigendian')) {
            obj.is_bigendian = d.is_bigendian;
        }
        if (d.hasOwnProperty('point_step')) {
            obj.point_step = d.point_step;
        }
        if (d.hasOwnProperty('row_step')) {
            obj.row_step = d.row_step;
        }
        if (d.hasOwnProperty('data')) {
            const item_class = uint8;
            if (Array.isArray(d.data)) {
                obj.data = d.data.map(item => item_class.fromDict(item));
            }
        }
        if (d.hasOwnProperty('is_dense')) {
            obj.is_dense = d.is_dense;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { PointCloud2 }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
