# Timestamp (UNIX Epoch time or time since system boot in microseconds)
uint32 time_usec

# Servo output port (0 = MAIN, 1 = AUX)
uint8 port

# Servo output values in microseconds
uint16 servo1_raw
uint16 servo2_raw
uint16 servo3_raw
uint16 servo4_raw
uint16 servo5_raw
uint16 servo6_raw
uint16 servo7_raw
uint16 servo8_raw
uint16 servo9_raw
uint16 servo10_raw
uint16 servo11_raw
uint16 servo12_raw
uint16 servo13_raw
uint16 servo14_raw
uint16 servo15_raw
uint16 servo16_raw
