

/**
 * ROS message: hako_mavlink_msgs/HakoSystemTime
 * Generated by hakoniwa-ros2pdu.
 */
export class HakoSystemTime {
/** @type { bigint } */
    time_unix_usec;
/** @type { bigint } */
    time_boot_ms;


    constructor() {
        this.time_unix_usec = 0n;
        this.time_boot_ms = 0n;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'time_unix_usec'
            const field_val = this.time_unix_usec;
            if (typeof field_val?.toDict === 'function') {
                d['time_unix_usec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['time_unix_usec'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['time_unix_usec'] = field_val;
            }
        }
        {
            // handle field 'time_boot_ms'
            const field_val = this.time_boot_ms;
            if (typeof field_val?.toDict === 'function') {
                d['time_boot_ms'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['time_boot_ms'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['time_boot_ms'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { HakoSystemTime }
     */
    static fromDict(d) {
        const obj = new HakoSystemTime();
        if (d.hasOwnProperty('time_unix_usec')) {
            obj.time_unix_usec = d.time_unix_usec;
        }
        if (d.hasOwnProperty('time_boot_ms')) {
            obj.time_boot_ms = d.time_boot_ms;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { HakoSystemTime }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
