

/**
 * ROS message: hako_mavlink_msgs/HakoSERVO_OUTPUT_RAW
 * Generated by hakoniwa-ros2pdu.
 */
export class HakoSERVO_OUTPUT_RAW {
/** @type { number } */
    time_usec;
/** @type { number } */
    port;
/** @type { number } */
    servo1_raw;
/** @type { number } */
    servo2_raw;
/** @type { number } */
    servo3_raw;
/** @type { number } */
    servo4_raw;
/** @type { number } */
    servo5_raw;
/** @type { number } */
    servo6_raw;
/** @type { number } */
    servo7_raw;
/** @type { number } */
    servo8_raw;


    constructor() {
        this.time_usec = 0;
        this.port = 0;
        this.servo1_raw = 0;
        this.servo2_raw = 0;
        this.servo3_raw = 0;
        this.servo4_raw = 0;
        this.servo5_raw = 0;
        this.servo6_raw = 0;
        this.servo7_raw = 0;
        this.servo8_raw = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'time_usec'
            const field_val = this.time_usec;
            if (typeof field_val?.toDict === 'function') {
                d['time_usec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['time_usec'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['time_usec'] = field_val;
            }
        }
        {
            // handle field 'port'
            const field_val = this.port;
            if (typeof field_val?.toDict === 'function') {
                d['port'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['port'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['port'] = field_val;
            }
        }
        {
            // handle field 'servo1_raw'
            const field_val = this.servo1_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo1_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo1_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo1_raw'] = field_val;
            }
        }
        {
            // handle field 'servo2_raw'
            const field_val = this.servo2_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo2_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo2_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo2_raw'] = field_val;
            }
        }
        {
            // handle field 'servo3_raw'
            const field_val = this.servo3_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo3_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo3_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo3_raw'] = field_val;
            }
        }
        {
            // handle field 'servo4_raw'
            const field_val = this.servo4_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo4_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo4_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo4_raw'] = field_val;
            }
        }
        {
            // handle field 'servo5_raw'
            const field_val = this.servo5_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo5_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo5_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo5_raw'] = field_val;
            }
        }
        {
            // handle field 'servo6_raw'
            const field_val = this.servo6_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo6_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo6_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo6_raw'] = field_val;
            }
        }
        {
            // handle field 'servo7_raw'
            const field_val = this.servo7_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo7_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo7_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo7_raw'] = field_val;
            }
        }
        {
            // handle field 'servo8_raw'
            const field_val = this.servo8_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo8_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo8_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo8_raw'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { HakoSERVO_OUTPUT_RAW }
     */
    static fromDict(d) {
        const obj = new HakoSERVO_OUTPUT_RAW();
        if (d.hasOwnProperty('time_usec')) {
            obj.time_usec = d.time_usec;
        }
        if (d.hasOwnProperty('port')) {
            obj.port = d.port;
        }
        if (d.hasOwnProperty('servo1_raw')) {
            obj.servo1_raw = d.servo1_raw;
        }
        if (d.hasOwnProperty('servo2_raw')) {
            obj.servo2_raw = d.servo2_raw;
        }
        if (d.hasOwnProperty('servo3_raw')) {
            obj.servo3_raw = d.servo3_raw;
        }
        if (d.hasOwnProperty('servo4_raw')) {
            obj.servo4_raw = d.servo4_raw;
        }
        if (d.hasOwnProperty('servo5_raw')) {
            obj.servo5_raw = d.servo5_raw;
        }
        if (d.hasOwnProperty('servo6_raw')) {
            obj.servo6_raw = d.servo6_raw;
        }
        if (d.hasOwnProperty('servo7_raw')) {
            obj.servo7_raw = d.servo7_raw;
        }
        if (d.hasOwnProperty('servo8_raw')) {
            obj.servo8_raw = d.servo8_raw;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { HakoSERVO_OUTPUT_RAW }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
