from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class ServiceRequestHeader:
    """
    ROS message: hako_srv_msgs/ServiceRequestHeader
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.request_id: int = 0
        self.service_name: str = ""
        self.client_name: str = ""
        self.opcode: int = 0
        self.status_poll_interval_msec: int = 0

    def __str__(self):
        return f"ServiceRequestHeader(" + ", ".join([
            f"request_id={self.request_id}"
            f"service_name={self.service_name}"
            f"client_name={self.client_name}"
            f"opcode={self.opcode}"
            f"status_poll_interval_msec={self.status_poll_interval_msec}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
