from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class SystemControlResponse:
    """
    ROS message: hako_srv_msgs/SystemControlResponse
    Generated by hakoniwa-ros2pdu.
    """

    status_code: int
    message: str

    def __init__(self):
        self.status_code = 0
        self.message = ""

    def __str__(self):
        return f"SystemControlResponse(" + ", ".join([
            f"status_code={self.status_code}"
            f"message={self.message}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'status_code'
        field_val = self.status_code
        if isinstance(field_val, bytearray):
            d['status_code'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['status_code'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['status_code'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['status_code'] = field_val
        # handle field 'message'
        field_val = self.message
        if isinstance(field_val, bytearray):
            d['message'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['message'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['message'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['message'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'status_code'
        if 'status_code' in d:
            field_type = cls.__annotations__.get('status_code')
            value = d['status_code']
            
            if field_type is bytearray:
                obj.status_code = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.status_code = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.status_code = value
            elif hasattr(field_type, 'from_dict'):
                obj.status_code = field_type.from_dict(value)
            else:
                obj.status_code = value
        # handle field 'message'
        if 'message' in d:
            field_type = cls.__annotations__.get('message')
            value = d['message']
            
            if field_type is bytearray:
                obj.message = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.message = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.message = value
            elif hasattr(field_type, 'from_dict'):
                obj.message = field_type.from_dict(value)
            else:
                obj.message = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
