from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class AddTwoIntsRequest:
    """
    ROS message: hako_srv_msgs/AddTwoIntsRequest
    Generated by hakoniwa-ros2pdu.
    """

    a: int
    b: int

    def __init__(self):
        self.a = 0
        self.b = 0

    def __str__(self):
        return f"AddTwoIntsRequest(" + ", ".join([
            f"a={self.a}"
            f"b={self.b}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'a'
        field_val = self.a
        if isinstance(field_val, bytearray):
            d['a'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['a'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['a'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['a'] = field_val
        # handle field 'b'
        field_val = self.b
        if isinstance(field_val, bytearray):
            d['b'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['b'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['b'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['b'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'a'
        if 'a' in d:
            field_type = cls.__annotations__.get('a')
            value = d['a']
            
            if field_type is bytearray:
                obj.a = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.a = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.a = value
            elif hasattr(field_type, 'from_dict'):
                obj.a = field_type.from_dict(value)
            else:
                obj.a = value
        # handle field 'b'
        if 'b' in d:
            field_type = cls.__annotations__.get('b')
            value = d['b']
            
            if field_type is bytearray:
                obj.b = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.b = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.b = value
            elif hasattr(field_type, 'from_dict'):
                obj.b = field_type.from_dict(value)
            else:
                obj.b = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
