from typing import List

# dependencies for the generated Python class

from ..hako_srv_msgs.pdu_pytype_AddTwoIntsRequest import AddTwoIntsRequest

from ..hako_srv_msgs.pdu_pytype_ServiceRequestHeader import ServiceRequestHeader


# class definition for the ROS message
class AddTwoIntsRequestPacket:
    """
    ROS message: hako_srv_msgs/AddTwoIntsRequestPacket
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.header: ServiceRequestHeader = ServiceRequestHeader()
        self.body: AddTwoIntsRequest = AddTwoIntsRequest()

    def __str__(self):
        return f"AddTwoIntsRequestPacket(" + ", ".join([
            f"header={self.header}"
            f"body={self.body}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
