from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class AddTwoIntsRequest:
    """
    ROS message: hako_srv_msgs/AddTwoIntsRequest
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.a: int = 0
        self.b: int = 0

    def __str__(self):
        return f"AddTwoIntsRequest(" + ", ".join([
            f"a={self.a}"
            f"b={self.b}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
