from typing import List

# dependencies for the generated Python class

from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class Twist:
    """
    ROS message: geometry_msgs/Twist
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.linear: Vector3 = Vector3()
        self.angular: Vector3 = Vector3()

    def __str__(self):
        return f"Twist(" + ", ".join([
            f"linear={self.linear}"
            f"angular={self.angular}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
