from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Quaternion:
    """
    ROS message: geometry_msgs/Quaternion
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.x: float = 0.0
        self.y: float = 0.0
        self.z: float = 0.0
        self.w: float = 0.0

    def __str__(self):
        return f"Quaternion(" + ", ".join([
            f"x={self.x}"
            f"y={self.y}"
            f"z={self.z}"
            f"w={self.w}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
