from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class RegionOfInterest:
    """
    ROS message: sensor_msgs/RegionOfInterest
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.x_offset: int = 0
        self.y_offset: int = 0
        self.height: int = 0
        self.width: int = 0
        self.do_rectify: bool = False

    def __str__(self):
        return f"RegionOfInterest(" + ", ".join([
            f"x_offset={self.x_offset}"
            f"y_offset={self.y_offset}"
            f"height={self.height}"
            f"width={self.width}"
            f"do_rectify={self.do_rectify}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
