from typing import List

# dependencies for the generated Python class

from ..std_msgs.pdu_pytype_Header import Header

from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class Image:
    """
    ROS message: sensor_msgs/Image
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.header: Header = Header()
        self.height: int = 0
        self.width: int = 0
        self.encoding: str = ""
        self.is_bigendian: int = 0
        self.step: int = 0
        self.data: List[int] = []

    def __str__(self):
        return f"Image(" + ", ".join([
            f"header={self.header}"
            f"height={self.height}"
            f"width={self.width}"
            f"encoding={self.encoding}"
            f"is_bigendian={self.is_bigendian}"
            f"step={self.step}"
            f"data={self.data}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
