from typing import List

# dependencies for the generated Python class

from ..std_msgs.pdu_pytype_Header import Header

from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class LaserScan:
    """
    ROS message: sensor_msgs/LaserScan
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.header: Header = Header()
        self.angle_min: float = 0.0
        self.angle_max: float = 0.0
        self.angle_increment: float = 0.0
        self.time_increment: float = 0.0
        self.scan_time: float = 0.0
        self.range_min: float = 0.0
        self.range_max: float = 0.0
        self.ranges: List[float] = []
        self.intensities: List[float] = []

    def __str__(self):
        return f"LaserScan(" + ", ".join([
            f"header={self.header}"
            f"angle_min={self.angle_min}"
            f"angle_max={self.angle_max}"
            f"angle_increment={self.angle_increment}"
            f"time_increment={self.time_increment}"
            f"scan_time={self.scan_time}"
            f"range_min={self.range_min}"
            f"range_max={self.range_max}"
            f"ranges={self.ranges}"
            f"intensities={self.intensities}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
