

/**
 * ROS message: hako_mavlink2_msgs/HakoSERVO_OUTPUT_RAW
 * Generated by hakoniwa-ros2pdu.
 */
export class HakoSERVO_OUTPUT_RAW {
/** @type { number } */
    time_usec;
/** @type { number } */
    port;
/** @type { number } */
    servo1_raw;
/** @type { number } */
    servo2_raw;
/** @type { number } */
    servo3_raw;
/** @type { number } */
    servo4_raw;
/** @type { number } */
    servo5_raw;
/** @type { number } */
    servo6_raw;
/** @type { number } */
    servo7_raw;
/** @type { number } */
    servo8_raw;
/** @type { number } */
    servo9_raw;
/** @type { number } */
    servo10_raw;
/** @type { number } */
    servo11_raw;
/** @type { number } */
    servo12_raw;
/** @type { number } */
    servo13_raw;
/** @type { number } */
    servo14_raw;
/** @type { number } */
    servo15_raw;
/** @type { number } */
    servo16_raw;


    constructor() {
        this.time_usec = 0;
        this.port = 0;
        this.servo1_raw = 0;
        this.servo2_raw = 0;
        this.servo3_raw = 0;
        this.servo4_raw = 0;
        this.servo5_raw = 0;
        this.servo6_raw = 0;
        this.servo7_raw = 0;
        this.servo8_raw = 0;
        this.servo9_raw = 0;
        this.servo10_raw = 0;
        this.servo11_raw = 0;
        this.servo12_raw = 0;
        this.servo13_raw = 0;
        this.servo14_raw = 0;
        this.servo15_raw = 0;
        this.servo16_raw = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'time_usec'
            const field_val = this.time_usec;
            if (typeof field_val?.toDict === 'function') {
                d['time_usec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['time_usec'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['time_usec'] = field_val;
            }
        }
        {
            // handle field 'port'
            const field_val = this.port;
            if (typeof field_val?.toDict === 'function') {
                d['port'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['port'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['port'] = field_val;
            }
        }
        {
            // handle field 'servo1_raw'
            const field_val = this.servo1_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo1_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo1_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo1_raw'] = field_val;
            }
        }
        {
            // handle field 'servo2_raw'
            const field_val = this.servo2_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo2_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo2_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo2_raw'] = field_val;
            }
        }
        {
            // handle field 'servo3_raw'
            const field_val = this.servo3_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo3_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo3_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo3_raw'] = field_val;
            }
        }
        {
            // handle field 'servo4_raw'
            const field_val = this.servo4_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo4_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo4_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo4_raw'] = field_val;
            }
        }
        {
            // handle field 'servo5_raw'
            const field_val = this.servo5_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo5_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo5_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo5_raw'] = field_val;
            }
        }
        {
            // handle field 'servo6_raw'
            const field_val = this.servo6_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo6_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo6_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo6_raw'] = field_val;
            }
        }
        {
            // handle field 'servo7_raw'
            const field_val = this.servo7_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo7_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo7_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo7_raw'] = field_val;
            }
        }
        {
            // handle field 'servo8_raw'
            const field_val = this.servo8_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo8_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo8_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo8_raw'] = field_val;
            }
        }
        {
            // handle field 'servo9_raw'
            const field_val = this.servo9_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo9_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo9_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo9_raw'] = field_val;
            }
        }
        {
            // handle field 'servo10_raw'
            const field_val = this.servo10_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo10_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo10_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo10_raw'] = field_val;
            }
        }
        {
            // handle field 'servo11_raw'
            const field_val = this.servo11_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo11_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo11_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo11_raw'] = field_val;
            }
        }
        {
            // handle field 'servo12_raw'
            const field_val = this.servo12_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo12_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo12_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo12_raw'] = field_val;
            }
        }
        {
            // handle field 'servo13_raw'
            const field_val = this.servo13_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo13_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo13_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo13_raw'] = field_val;
            }
        }
        {
            // handle field 'servo14_raw'
            const field_val = this.servo14_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo14_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo14_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo14_raw'] = field_val;
            }
        }
        {
            // handle field 'servo15_raw'
            const field_val = this.servo15_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo15_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo15_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo15_raw'] = field_val;
            }
        }
        {
            // handle field 'servo16_raw'
            const field_val = this.servo16_raw;
            if (typeof field_val?.toDict === 'function') {
                d['servo16_raw'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['servo16_raw'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['servo16_raw'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { HakoSERVO_OUTPUT_RAW }
     */
    static fromDict(d) {
        const obj = new HakoSERVO_OUTPUT_RAW();
        if (d.hasOwnProperty('time_usec')) {
            obj.time_usec = d.time_usec;
        }
        if (d.hasOwnProperty('port')) {
            obj.port = d.port;
        }
        if (d.hasOwnProperty('servo1_raw')) {
            obj.servo1_raw = d.servo1_raw;
        }
        if (d.hasOwnProperty('servo2_raw')) {
            obj.servo2_raw = d.servo2_raw;
        }
        if (d.hasOwnProperty('servo3_raw')) {
            obj.servo3_raw = d.servo3_raw;
        }
        if (d.hasOwnProperty('servo4_raw')) {
            obj.servo4_raw = d.servo4_raw;
        }
        if (d.hasOwnProperty('servo5_raw')) {
            obj.servo5_raw = d.servo5_raw;
        }
        if (d.hasOwnProperty('servo6_raw')) {
            obj.servo6_raw = d.servo6_raw;
        }
        if (d.hasOwnProperty('servo7_raw')) {
            obj.servo7_raw = d.servo7_raw;
        }
        if (d.hasOwnProperty('servo8_raw')) {
            obj.servo8_raw = d.servo8_raw;
        }
        if (d.hasOwnProperty('servo9_raw')) {
            obj.servo9_raw = d.servo9_raw;
        }
        if (d.hasOwnProperty('servo10_raw')) {
            obj.servo10_raw = d.servo10_raw;
        }
        if (d.hasOwnProperty('servo11_raw')) {
            obj.servo11_raw = d.servo11_raw;
        }
        if (d.hasOwnProperty('servo12_raw')) {
            obj.servo12_raw = d.servo12_raw;
        }
        if (d.hasOwnProperty('servo13_raw')) {
            obj.servo13_raw = d.servo13_raw;
        }
        if (d.hasOwnProperty('servo14_raw')) {
            obj.servo14_raw = d.servo14_raw;
        }
        if (d.hasOwnProperty('servo15_raw')) {
            obj.servo15_raw = d.servo15_raw;
        }
        if (d.hasOwnProperty('servo16_raw')) {
            obj.servo16_raw = d.servo16_raw;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { HakoSERVO_OUTPUT_RAW }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
