from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoCanHead:
    """
    ROS message: can_msgs/HakoCanHead
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.channel: int = 0
        self.ide: int = 0
        self.rtr: int = 0
        self.dlc: int = 0
        self.canid: int = 0

    def __str__(self):
        return f"HakoCanHead(" + ", ".join([
            f"channel={self.channel}"
            f"ide={self.ide}"
            f"rtr={self.rtr}"
            f"dlc={self.dlc}"
            f"canid={self.canid}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
