import { Vector3 } from '../geometry_msgs/pdu_jstype_Vector3.js';


/**
 * ROS message: hako_msgs/HakoCameraInfo
 * Generated by hakoniwa-ros2pdu.
 */
export class HakoCameraInfo {
/** @type { number } */
    request_id;
/** @type { Vector3 } */
    angle;


    constructor() {
        this.request_id = 0;
        this.angle = null;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'request_id'
            const field_val = this.request_id;
            if (typeof field_val?.toDict === 'function') {
                d['request_id'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['request_id'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['request_id'] = field_val;
            }
        }
        {
            // handle field 'angle'
            const field_val = this.angle;
            if (typeof field_val?.toDict === 'function') {
                d['angle'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['angle'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['angle'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { HakoCameraInfo }
     */
    static fromDict(d) {
        const obj = new HakoCameraInfo();
        if (d.hasOwnProperty('request_id')) {
            obj.request_id = d.request_id;
        }
        if (d.hasOwnProperty('angle')) {
            const field_class = Vector3;
            if (d.angle) {
                obj.angle = field_class.fromDict(d.angle);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { HakoCameraInfo }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
