

/**
 * ROS message: hako_msgs/SimpleVarray
 * Generated by hakoniwa-ros2pdu.
 */
export class SimpleVarray {
/** @type { Array<number> } */
    data;
/** @type { Array<number> } */
    fixed_array;
/** @type { number } */
    p_mem1;


    constructor() {
        this.data = [];
        this.fixed_array = [];
        this.p_mem1 = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'data'
            const field_val = this.data;
            if (typeof field_val?.toDict === 'function') {
                d['data'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['data'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['data'] = field_val;
            }
        }
        {
            // handle field 'fixed_array'
            const field_val = this.fixed_array;
            if (typeof field_val?.toDict === 'function') {
                d['fixed_array'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['fixed_array'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['fixed_array'] = field_val;
            }
        }
        {
            // handle field 'p_mem1'
            const field_val = this.p_mem1;
            if (typeof field_val?.toDict === 'function') {
                d['p_mem1'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['p_mem1'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['p_mem1'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { SimpleVarray }
     */
    static fromDict(d) {
        const obj = new SimpleVarray();
        if (d.hasOwnProperty('data')) {
            const item_class = int8;
            if (Array.isArray(d.data)) {
                obj.data = d.data.map(item => item_class.fromDict(item));
            }
        }
        if (d.hasOwnProperty('fixed_array')) {
            const item_class = int8;
            if (Array.isArray(d.fixed_array)) {
                obj.fixed_array = d.fixed_array.map(item => item_class.fromDict(item));
            }
        }
        if (d.hasOwnProperty('p_mem1')) {
            obj.p_mem1 = d.p_mem1;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { SimpleVarray }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
