

/**
 * ROS message: hako_msgs/HakoCmdHeader
 * Generated by hakoniwa-ros2pdu.
 */
export class HakoCmdHeader {
/** @type { boolean } */
    request;
/** @type { boolean } */
    result;
/** @type { number } */
    result_code;


    constructor() {
        this.request = false;
        this.result = false;
        this.result_code = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'request'
            const field_val = this.request;
            if (typeof field_val?.toDict === 'function') {
                d['request'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['request'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['request'] = field_val;
            }
        }
        {
            // handle field 'result'
            const field_val = this.result;
            if (typeof field_val?.toDict === 'function') {
                d['result'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['result'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['result'] = field_val;
            }
        }
        {
            // handle field 'result_code'
            const field_val = this.result_code;
            if (typeof field_val?.toDict === 'function') {
                d['result_code'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['result_code'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['result_code'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { HakoCmdHeader }
     */
    static fromDict(d) {
        const obj = new HakoCmdHeader();
        if (d.hasOwnProperty('request')) {
            obj.request = d.request;
        }
        if (d.hasOwnProperty('result')) {
            obj.result = d.result;
        }
        if (d.hasOwnProperty('result_code')) {
            obj.result_code = d.result_code;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { HakoCmdHeader }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
