import { Point } from '../geometry_msgs/pdu_jstype_Point.js';
import { Pose } from '../geometry_msgs/pdu_jstype_Pose.js';
import { Quaternion } from '../geometry_msgs/pdu_jstype_Quaternion.js';


/**
 * ROS message: geometry_msgs/PoseWithCovariance
 * Generated by hakoniwa-ros2pdu.
 */
export class PoseWithCovariance {
/** @type { Pose } */
    pose;
/** @type { Array<number> } */
    covariance;


    constructor() {
        this.pose = null;
        this.covariance = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'pose'
            const field_val = this.pose;
            if (typeof field_val?.toDict === 'function') {
                d['pose'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['pose'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['pose'] = field_val;
            }
        }
        {
            // handle field 'covariance'
            const field_val = this.covariance;
            if (typeof field_val?.toDict === 'function') {
                d['covariance'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['covariance'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['covariance'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { PoseWithCovariance }
     */
    static fromDict(d) {
        const obj = new PoseWithCovariance();
        if (d.hasOwnProperty('pose')) {
            const field_class = Pose;
            if (d.pose) {
                obj.pose = field_class.fromDict(d.pose);
            }
        }
        if (d.hasOwnProperty('covariance')) {
            const item_class = float64;
            if (Array.isArray(d.covariance)) {
                obj.covariance = d.covariance.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { PoseWithCovariance }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
