import { Header } from '../std_msgs/pdu_jstype_Header.js';
import { Quaternion } from '../geometry_msgs/pdu_jstype_Quaternion.js';
import { Time } from '../builtin_interfaces/pdu_jstype_Time.js';
import { Transform } from '../geometry_msgs/pdu_jstype_Transform.js';
import { Vector3 } from '../geometry_msgs/pdu_jstype_Vector3.js';


/**
 * ROS message: geometry_msgs/TransformStamped
 * Generated by hakoniwa-ros2pdu.
 */
export class TransformStamped {
/** @type { Header } */
    header;
/** @type { string } */
    child_frame_id;
/** @type { Transform } */
    transform;


    constructor() {
        this.header = new Header();
        this.child_frame_id = "";
        this.transform = new Transform();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'child_frame_id'
            const field_val = this.child_frame_id;
            if (typeof field_val?.toDict === 'function') {
                d['child_frame_id'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['child_frame_id'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['child_frame_id'] = field_val;
            }
        }
        {
            // handle field 'transform'
            const field_val = this.transform;
            if (typeof field_val?.toDict === 'function') {
                d['transform'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['transform'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['transform'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { TransformStamped }
     */
    static fromDict(d) {
        const obj = new TransformStamped();
        if (d.hasOwnProperty('header')) {
            const field_class = Header;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('child_frame_id')) {
            obj.child_frame_id = d.child_frame_id;
        }
        if (d.hasOwnProperty('transform')) {
            const field_class = Transform;
            if (d.transform) {
                obj.transform = field_class.fromDict(d.transform);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { TransformStamped }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
