import { MultiArrayDimension } from '../std_msgs/pdu_jstype_MultiArrayDimension.js';
import { MultiArrayLayout } from '../std_msgs/pdu_jstype_MultiArrayLayout.js';


/**
 * ROS message: std_msgs/Int8MultiArray
 * Generated by hakoniwa-ros2pdu.
 */
export class Int8MultiArray {
/** @type { MultiArrayLayout } */
    layout;
/** @type { Array<number> } */
    data;


    constructor() {
        this.layout = null;
        this.data = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'layout'
            const field_val = this.layout;
            if (typeof field_val?.toDict === 'function') {
                d['layout'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['layout'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['layout'] = field_val;
            }
        }
        {
            // handle field 'data'
            const field_val = this.data;
            if (typeof field_val?.toDict === 'function') {
                d['data'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['data'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['data'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { Int8MultiArray }
     */
    static fromDict(d) {
        const obj = new Int8MultiArray();
        if (d.hasOwnProperty('layout')) {
            const field_class = MultiArrayLayout;
            if (d.layout) {
                obj.layout = field_class.fromDict(d.layout);
            }
        }
        if (d.hasOwnProperty('data')) {
            const item_class = int8;
            if (Array.isArray(d.data)) {
                obj.data = d.data.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { Int8MultiArray }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
