import { MultiArrayDimension } from '../std_msgs/pdu_jstype_MultiArrayDimension.js';


/**
 * ROS message: std_msgs/MultiArrayLayout
 * Generated by hakoniwa-ros2pdu.
 */
export class MultiArrayLayout {
/** @type { Array<MultiArrayDimension> } */
    dim;
/** @type { number } */
    data_offset;


    constructor() {
        this.dim = [];
        this.data_offset = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'dim'
            const field_val = this.dim;
            if (typeof field_val?.toDict === 'function') {
                d['dim'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['dim'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['dim'] = field_val;
            }
        }
        {
            // handle field 'data_offset'
            const field_val = this.data_offset;
            if (typeof field_val?.toDict === 'function') {
                d['data_offset'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['data_offset'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['data_offset'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { MultiArrayLayout }
     */
    static fromDict(d) {
        const obj = new MultiArrayLayout();
        if (d.hasOwnProperty('dim')) {
            const item_class = MultiArrayDimension;
            if (Array.isArray(d.dim)) {
                obj.dim = d.dim.map(item => item_class.fromDict(item));
            }
        }
        if (d.hasOwnProperty('data_offset')) {
            obj.data_offset = d.data_offset;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { MultiArrayLayout }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
