

/**
 * ROS message: std_msgs/UInt16
 * Generated by hakoniwa-ros2pdu.
 */
export class UInt16 {
/** @type { number } */
    data;


    constructor() {
        this.data = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'data'
            const field_val = this.data;
            if (typeof field_val?.toDict === 'function') {
                d['data'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['data'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['data'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { UInt16 }
     */
    static fromDict(d) {
        const obj = new UInt16();
        if (d.hasOwnProperty('data')) {
            obj.data = d.data;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { UInt16 }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
