from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Ev3PduColorSensor:
    """
    ROS message: ev3_msgs/Ev3PduColorSensor
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.color: int = 0
        self.reflect: int = 0
        self.rgb_r: int = 0
        self.rgb_g: int = 0
        self.rgb_b: int = 0

    def __str__(self):
        return f"Ev3PduColorSensor(" + ", ".join([
            f"color={self.color}"
            f"reflect={self.reflect}"
            f"rgb_r={self.rgb_r}"
            f"rgb_g={self.rgb_g}"
            f"rgb_b={self.rgb_b}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
