from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Ev3PduActuatorHeader:
    """
    ROS message: ev3_msgs/Ev3PduActuatorHeader
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.name: str = ""
        self.version: int = 0
        self.asset_time: int = 0
        self.ext_off: int = 0
        self.ext_size: int = 0

    def __str__(self):
        return f"Ev3PduActuatorHeader(" + ", ".join([
            f"name={self.name}"
            f"version={self.version}"
            f"asset_time={self.asset_time}"
            f"ext_off={self.ext_off}"
            f"ext_size={self.ext_size}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
