from typing import List

# dependencies for the generated Python class

from ..ev3_msgs.pdu_pytype_Ev3PduActuatorHeader import Ev3PduActuatorHeader

from ..ev3_msgs.pdu_pytype_Ev3PduMotor import Ev3PduMotor


# class definition for the ROS message
class Ev3PduActuator:
    """
    ROS message: ev3_msgs/Ev3PduActuator
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.head: Ev3PduActuatorHeader = Ev3PduActuatorHeader()
        self.leds: List[int] = []
        self.motors: List[Ev3PduMotor] = []
        self.gyro_reset: int = 0

    def __str__(self):
        return f"Ev3PduActuator(" + ", ".join([
            f"head={self.head}"
            f"leds={self.leds}"
            f"motors={self.motors}"
            f"gyro_reset={self.gyro_reset}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
