from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Ev3PduMotor:
    """
    ROS message: ev3_msgs/Ev3PduMotor
    Generated by hakoniwa-ros2pdu.
    """

    power: int
    stop: int
    reset_angle: int

    def __init__(self):
        self.power = 0
        self.stop = 0
        self.reset_angle = 0

    def __str__(self):
        return f"Ev3PduMotor(" + ", ".join([
            f"power={self.power}"
            f"stop={self.stop}"
            f"reset_angle={self.reset_angle}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'power'
        field_val = self.power
        if isinstance(field_val, bytearray):
            d['power'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['power'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['power'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['power'] = field_val
        # handle field 'stop'
        field_val = self.stop
        if isinstance(field_val, bytearray):
            d['stop'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['stop'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['stop'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['stop'] = field_val
        # handle field 'reset_angle'
        field_val = self.reset_angle
        if isinstance(field_val, bytearray):
            d['reset_angle'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['reset_angle'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['reset_angle'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['reset_angle'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'power'
        if 'power' in d:
            field_type = cls.__annotations__.get('power')
            value = d['power']
            
            if field_type is bytearray:
                obj.power = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.power = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.power = value
            elif hasattr(field_type, 'from_dict'):
                obj.power = field_type.from_dict(value)
            else:
                obj.power = value
        # handle field 'stop'
        if 'stop' in d:
            field_type = cls.__annotations__.get('stop')
            value = d['stop']
            
            if field_type is bytearray:
                obj.stop = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.stop = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.stop = value
            elif hasattr(field_type, 'from_dict'):
                obj.stop = field_type.from_dict(value)
            else:
                obj.stop = value
        # handle field 'reset_angle'
        if 'reset_angle' in d:
            field_type = cls.__annotations__.get('reset_angle')
            value = d['reset_angle']
            
            if field_type is bytearray:
                obj.reset_angle = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.reset_angle = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.reset_angle = value
            elif hasattr(field_type, 'from_dict'):
                obj.reset_angle = field_type.from_dict(value)
            else:
                obj.reset_angle = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
