import { HakoCanBody } from '../can_msgs/pdu_jstype_HakoCanBody.js';
import { HakoCanHead } from '../can_msgs/pdu_jstype_HakoCanHead.js';


/**
 * ROS message: can_msgs/HakoCan
 * Generated by hakoniwa-ros2pdu.
 */
export class HakoCan {
/** @type { HakoCanHead } */
    head;
/** @type { HakoCanBody } */
    body;


    constructor() {
        this.head = null;
        this.body = null;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'head'
            const field_val = this.head;
            if (typeof field_val?.toDict === 'function') {
                d['head'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['head'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['head'] = field_val;
            }
        }
        {
            // handle field 'body'
            const field_val = this.body;
            if (typeof field_val?.toDict === 'function') {
                d['body'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['body'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['body'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { HakoCan }
     */
    static fromDict(d) {
        const obj = new HakoCan();
        if (d.hasOwnProperty('head')) {
            const field_class = HakoCanHead;
            if (d.head) {
                obj.head = field_class.fromDict(d.head);
            }
        }
        if (d.hasOwnProperty('body')) {
            const field_class = HakoCanBody;
            if (d.body) {
                obj.body = field_class.fromDict(d.body);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { HakoCan }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
