

/**
 * ROS message: can_msgs/HakoCanBody
 * Generated by hakoniwa-ros2pdu.
 */
export class HakoCanBody {
/** @type { Array<number> } */
    data;


    constructor() {
        this.data = [];
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'data'
            const field_val = this.data;
            if (typeof field_val?.toDict === 'function') {
                d['data'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['data'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['data'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { HakoCanBody }
     */
    static fromDict(d) {
        const obj = new HakoCanBody();
        if (d.hasOwnProperty('data')) {
            const item_class = uint8;
            if (Array.isArray(d.data)) {
                obj.data = d.data.map(item => item_class.fromDict(item));
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { HakoCanBody }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
