

/**
 * ROS message: hako_srv_msgs/RegisterClientRequest
 * Generated by hakoniwa-ros2pdu.
 */
export class RegisterClientRequest {
/** @type { number } */
    dummy;


    constructor() {
        this.dummy = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'dummy'
            const field_val = this.dummy;
            if (typeof field_val?.toDict === 'function') {
                d['dummy'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['dummy'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['dummy'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { RegisterClientRequest }
     */
    static fromDict(d) {
        const obj = new RegisterClientRequest();
        if (d.hasOwnProperty('dummy')) {
            obj.dummy = d.dummy;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { RegisterClientRequest }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
