

/**
 * ROS message: hako_srv_msgs/ServiceRequestHeader
 * Generated by hakoniwa-ros2pdu.
 */
export class ServiceRequestHeader {
/** @type { number } */
    request_id;
/** @type { string } */
    service_name;
/** @type { string } */
    client_name;
/** @type { number } */
    opcode;
/** @type { number } */
    status_poll_interval_msec;


    constructor() {
        this.request_id = 0;
        this.service_name = "";
        this.client_name = "";
        this.opcode = 0;
        this.status_poll_interval_msec = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'request_id'
            const field_val = this.request_id;
            if (typeof field_val?.toDict === 'function') {
                d['request_id'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['request_id'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['request_id'] = field_val;
            }
        }
        {
            // handle field 'service_name'
            const field_val = this.service_name;
            if (typeof field_val?.toDict === 'function') {
                d['service_name'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['service_name'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['service_name'] = field_val;
            }
        }
        {
            // handle field 'client_name'
            const field_val = this.client_name;
            if (typeof field_val?.toDict === 'function') {
                d['client_name'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['client_name'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['client_name'] = field_val;
            }
        }
        {
            // handle field 'opcode'
            const field_val = this.opcode;
            if (typeof field_val?.toDict === 'function') {
                d['opcode'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['opcode'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['opcode'] = field_val;
            }
        }
        {
            // handle field 'status_poll_interval_msec'
            const field_val = this.status_poll_interval_msec;
            if (typeof field_val?.toDict === 'function') {
                d['status_poll_interval_msec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['status_poll_interval_msec'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['status_poll_interval_msec'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { ServiceRequestHeader }
     */
    static fromDict(d) {
        const obj = new ServiceRequestHeader();
        if (d.hasOwnProperty('request_id')) {
            obj.request_id = d.request_id;
        }
        if (d.hasOwnProperty('service_name')) {
            obj.service_name = d.service_name;
        }
        if (d.hasOwnProperty('client_name')) {
            obj.client_name = d.client_name;
        }
        if (d.hasOwnProperty('opcode')) {
            obj.opcode = d.opcode;
        }
        if (d.hasOwnProperty('status_poll_interval_msec')) {
            obj.status_poll_interval_msec = d.status_poll_interval_msec;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { ServiceRequestHeader }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
