from typing import List

# dependencies for the generated Python class

from ..geometry_msgs.pdu_pytype_Point import Point

from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class Collision:
    """
    ROS message: hako_msgs/Collision
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.collision: bool = False
        self.contact_num: int = 0
        self.relative_velocity: Vector3 = Vector3()
        self.contact_position: List[Point] = []
        self.restitution_coefficient: float = 0.0

    def __str__(self):
        return f"Collision(" + ", ".join([
            f"collision={self.collision}"
            f"contact_num={self.contact_num}"
            f"relative_velocity={self.relative_velocity}"
            f"contact_position={self.contact_position}"
            f"restitution_coefficient={self.restitution_coefficient}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
