from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoBatteryStatus:
    """
    ROS message: hako_msgs/HakoBatteryStatus
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.full_voltage: float = 0.0
        self.curr_voltage: float = 0.0
        self.curr_temp: float = 0.0
        self.status: int = 0
        self.cycles: int = 0

    def __str__(self):
        return f"HakoBatteryStatus(" + ", ".join([
            f"full_voltage={self.full_voltage}"
            f"curr_voltage={self.curr_voltage}"
            f"curr_temp={self.curr_temp}"
            f"status={self.status}"
            f"cycles={self.cycles}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
