from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoCmdHeader:
    """
    ROS message: hako_msgs/HakoCmdHeader
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.request: bool = False
        self.result: bool = False
        self.result_code: int = 0

    def __str__(self):
        return f"HakoCmdHeader(" + ", ".join([
            f"request={self.request}"
            f"result={self.result}"
            f"result_code={self.result_code}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
