from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class SimpleVarray:
    """
    ROS message: hako_msgs/SimpleVarray
    Generated by hakoniwa-ros2pdu.
    """

    data: List[int]
    fixed_array: List[int]
    p_mem1: int

    def __init__(self):
        self.data = []
        self.fixed_array = []
        self.p_mem1 = 0

    def __str__(self):
        return f"SimpleVarray(" + ", ".join([
            f"data={self.data}"
            f"fixed_array={self.fixed_array}"
            f"p_mem1={self.p_mem1}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'data'
        field_val = self.data
        if isinstance(field_val, bytearray):
            d['data'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['data'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['data'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['data'] = field_val
        # handle field 'fixed_array'
        field_val = self.fixed_array
        if isinstance(field_val, bytearray):
            d['fixed_array'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['fixed_array'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['fixed_array'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['fixed_array'] = field_val
        # handle field 'p_mem1'
        field_val = self.p_mem1
        if isinstance(field_val, bytearray):
            d['p_mem1'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['p_mem1'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['p_mem1'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['p_mem1'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'data'
        if 'data' in d:
            field_type = cls.__annotations__.get('data')
            value = d['data']
            
            if field_type is bytearray:
                obj.data = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.data = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.data = value
            elif hasattr(field_type, 'from_dict'):
                obj.data = field_type.from_dict(value)
            else:
                obj.data = value
        # handle field 'fixed_array'
        if 'fixed_array' in d:
            field_type = cls.__annotations__.get('fixed_array')
            value = d['fixed_array']
            
            if field_type is bytearray:
                obj.fixed_array = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.fixed_array = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.fixed_array = value
            elif hasattr(field_type, 'from_dict'):
                obj.fixed_array = field_type.from_dict(value)
            else:
                obj.fixed_array = value
        # handle field 'p_mem1'
        if 'p_mem1' in d:
            field_type = cls.__annotations__.get('p_mem1')
            value = d['p_mem1']
            
            if field_type is bytearray:
                obj.p_mem1 = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.p_mem1 = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.p_mem1 = value
            elif hasattr(field_type, 'from_dict'):
                obj.p_mem1 = field_type.from_dict(value)
            else:
                obj.p_mem1 = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
