from typing import List

# dependencies for the generated Python class

from ..geometry_msgs.pdu_pytype_Point import Point

from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class ImpulseCollision:
    """
    ROS message: hako_msgs/ImpulseCollision
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.collision: bool = False
        self.is_target_static: bool = False
        self.restitution_coefficient: float = 0.0
        self.self_contact_vector: Point = Point()
        self.normal: Vector3 = Vector3()
        self.target_contact_vector: Point = Point()
        self.target_velocity: Vector3 = Vector3()
        self.target_angular_velocity: Vector3 = Vector3()
        self.target_euler: Vector3 = Vector3()
        self.target_inertia: Vector3 = Vector3()
        self.target_mass: float = 0.0

    def __str__(self):
        return f"ImpulseCollision(" + ", ".join([
            f"collision={self.collision}"
            f"is_target_static={self.is_target_static}"
            f"restitution_coefficient={self.restitution_coefficient}"
            f"self_contact_vector={self.self_contact_vector}"
            f"normal={self.normal}"
            f"target_contact_vector={self.target_contact_vector}"
            f"target_velocity={self.target_velocity}"
            f"target_angular_velocity={self.target_angular_velocity}"
            f"target_euler={self.target_euler}"
            f"target_inertia={self.target_inertia}"
            f"target_mass={self.target_mass}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
