from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class DisturbanceTemperature:
    """
    ROS message: hako_msgs/DisturbanceTemperature
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.value: float = 0.0

    def __str__(self):
        return f"DisturbanceTemperature(" + ", ".join([
            f"value={self.value}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
