from typing import List

# dependencies for the generated Python class
from ..hako_msgs.pdu_pytype_HakoCmdHeader import HakoCmdHeader


# class definition for the ROS message
class HakoCmdMagnetHolder:
    """
    ROS message: hako_msgs/HakoCmdMagnetHolder
    Generated by hakoniwa-ros2pdu.
    """

    header: HakoCmdHeader
    magnet_on: bool

    def __init__(self):
        self.header = HakoCmdHeader()
        self.magnet_on = False

    def __str__(self):
        return f"HakoCmdMagnetHolder(" + ", ".join([
            f"header={self.header}"
            f"magnet_on={self.magnet_on}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'header'
        field_val = self.header
        if isinstance(field_val, bytearray):
            d['header'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['header'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['header'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['header'] = field_val
        # handle field 'magnet_on'
        field_val = self.magnet_on
        if isinstance(field_val, bytearray):
            d['magnet_on'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['magnet_on'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['magnet_on'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['magnet_on'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'header'
        if 'header' in d:
            field_type = cls.__annotations__.get('header')
            value = d['header']
            
            if field_type is bytearray:
                obj.header = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.header = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.header = value
            elif hasattr(field_type, 'from_dict'):
                obj.header = field_type.from_dict(value)
            else:
                obj.header = value
        # handle field 'magnet_on'
        if 'magnet_on' in d:
            field_type = cls.__annotations__.get('magnet_on')
            value = d['magnet_on']
            
            if field_type is bytearray:
                obj.magnet_on = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.magnet_on = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.magnet_on = value
            elif hasattr(field_type, 'from_dict'):
                obj.magnet_on = field_type.from_dict(value)
            else:
                obj.magnet_on = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
