from typing import List

# dependencies for the generated Python class

from ..sensor_msgs.pdu_pytype_CompressedImage import CompressedImage

from ..std_msgs.pdu_pytype_Header import Header

from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class HakoCameraData:
    """
    ROS message: hako_msgs/HakoCameraData
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.request_id: int = 0
        self.image: CompressedImage = CompressedImage()

    def __str__(self):
        return f"HakoCameraData(" + ", ".join([
            f"request_id={self.request_id}"
            f"image={self.image}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
