from typing import List

# dependencies for the generated Python class

from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class DisturbanceWind:
    """
    ROS message: hako_msgs/DisturbanceWind
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.value: Vector3 = Vector3()

    def __str__(self):
        return f"DisturbanceWind(" + ", ".join([
            f"value={self.value}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
