from typing import List

# dependencies for the generated Python class

from ..hako_msgs.pdu_pytype_HakoDroneCmdHeader import HakoDroneCmdHeader


# class definition for the ROS message
class HakoDroneCmdMove:
    """
    ROS message: hako_msgs/HakoDroneCmdMove
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.header: HakoDroneCmdHeader = HakoDroneCmdHeader()
        self.x: float = 0.0
        self.y: float = 0.0
        self.z: float = 0.0
        self.speed: float = 0.0
        self.yaw_deg: float = 0.0

    def __str__(self):
        return f"HakoDroneCmdMove(" + ", ".join([
            f"header={self.header}"
            f"x={self.x}"
            f"y={self.y}"
            f"z={self.z}"
            f"speed={self.speed}"
            f"yaw_deg={self.yaw_deg}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
