from typing import List

# dependencies for the generated Python class
from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class DisturbanceWind:
    """
    ROS message: hako_msgs/DisturbanceWind
    Generated by hakoniwa-ros2pdu.
    """

    value: Vector3

    def __init__(self):
        self.value = Vector3()

    def __str__(self):
        return f"DisturbanceWind(" + ", ".join([
            f"value={self.value}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'value'
        field_val = self.value
        if isinstance(field_val, bytearray):
            d['value'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['value'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['value'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['value'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'value'
        if 'value' in d:
            field_type = cls.__annotations__.get('value')
            value = d['value']
            
            if field_type is bytearray:
                obj.value = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.value = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.value = value
            elif hasattr(field_type, 'from_dict'):
                obj.value = field_type.from_dict(value)
            else:
                obj.value = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
