from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class HakoStatusMagnetHolder:
    """
    ROS message: hako_msgs/HakoStatusMagnetHolder
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.magnet_on: bool = False
        self.contact_on: bool = False

    def __str__(self):
        return f"HakoStatusMagnetHolder(" + ", ".join([
            f"magnet_on={self.magnet_on}"
            f"contact_on={self.contact_on}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
