from typing import List

# dependencies for the generated Python class

from ..hako_msgs.pdu_pytype_HakoDroneCmdHeader import HakoDroneCmdHeader


# class definition for the ROS message
class HakoDroneCmdLand:
    """
    ROS message: hako_msgs/HakoDroneCmdLand
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.header: HakoDroneCmdHeader = HakoDroneCmdHeader()
        self.height: float = 0.0
        self.speed: float = 0.0
        self.yaw_deg: float = 0.0

    def __str__(self):
        return f"HakoDroneCmdLand(" + ", ".join([
            f"header={self.header}"
            f"height={self.height}"
            f"speed={self.speed}"
            f"yaw_deg={self.yaw_deg}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
