from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class SimpleVarray:
    """
    ROS message: hako_msgs/SimpleVarray
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.data: List[int] = []
        self.fixed_array: List[int] = []
        self.p_mem1: int = 0

    def __str__(self):
        return f"SimpleVarray(" + ", ".join([
            f"data={self.data}"
            f"fixed_array={self.fixed_array}"
            f"p_mem1={self.p_mem1}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
