from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class ShareObjectOwnerResponse:
    """
    ROS message: hako_msgs/ShareObjectOwnerResponse
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.object_name: str = ""
        self.request_type: int = 0
        self.owner_id: int = 0
        self.accepted: bool = False

    def __str__(self):
        return f"ShareObjectOwnerResponse(" + ", ".join([
            f"object_name={self.object_name}"
            f"request_type={self.request_type}"
            f"owner_id={self.owner_id}"
            f"accepted={self.accepted}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
