from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class DisturbanceAtm:
    """
    ROS message: hako_msgs/DisturbanceAtm
    Generated by hakoniwa-ros2pdu.
    """

    sea_level_atm: float

    def __init__(self):
        self.sea_level_atm = 0.0

    def __str__(self):
        return f"DisturbanceAtm(" + ", ".join([
            f"sea_level_atm={self.sea_level_atm}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'sea_level_atm'
        field_val = self.sea_level_atm
        if isinstance(field_val, bytearray):
            d['sea_level_atm'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['sea_level_atm'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['sea_level_atm'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['sea_level_atm'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'sea_level_atm'
        if 'sea_level_atm' in d:
            field_type = cls.__annotations__.get('sea_level_atm')
            value = d['sea_level_atm']
            
            if field_type is bytearray:
                obj.sea_level_atm = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.sea_level_atm = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.sea_level_atm = value
            elif hasattr(field_type, 'from_dict'):
                obj.sea_level_atm = field_type.from_dict(value)
            else:
                obj.sea_level_atm = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
