from typing import List

# dependencies for the generated Python class

from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class HakoCameraInfo:
    """
    ROS message: hako_msgs/HakoCameraInfo
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.request_id: int = 0
        self.angle: Vector3 = Vector3()

    def __str__(self):
        return f"HakoCameraInfo(" + ", ".join([
            f"request_id={self.request_id}"
            f"angle={self.angle}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
