from typing import List

# dependencies for the generated Python class

from ..geometry_msgs.pdu_pytype_Twist import Twist

from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class ShareObjectOwner:
    """
    ROS message: hako_msgs/ShareObjectOwner
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.object_name: str = ""
        self.owner_id: int = 0
        self.last_update: int = 0
        self.pos: Twist = Twist()

    def __str__(self):
        return f"ShareObjectOwner(" + ", ".join([
            f"object_name={self.object_name}"
            f"owner_id={self.owner_id}"
            f"last_update={self.last_update}"
            f"pos={self.pos}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
