from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class GameControllerOperation:
    """
    ROS message: hako_msgs/GameControllerOperation
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.axis: List[float] = []
        self.button: List[bool] = []

    def __str__(self):
        return f"GameControllerOperation(" + ", ".join([
            f"axis={self.axis}"
            f"button={self.button}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
