from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class DisturbanceAtm:
    """
    ROS message: hako_msgs/DisturbanceAtm
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.sea_level_atm: float = 0.0

    def __str__(self):
        return f"DisturbanceAtm(" + ", ".join([
            f"sea_level_atm={self.sea_level_atm}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
