from typing import List

# dependencies for the generated Python class

from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class DroneStatus:
    """
    ROS message: hako_msgs/DroneStatus
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.flight_mode: int = 0
        self.internal_state: int = 0
        self.propeller_wind: Vector3 = Vector3()

    def __str__(self):
        return f"DroneStatus(" + ", ".join([
            f"flight_mode={self.flight_mode}"
            f"internal_state={self.internal_state}"
            f"propeller_wind={self.propeller_wind}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
