from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class DisturbanceUserCustom:
    """
    ROS message: hako_msgs/DisturbanceUserCustom
    Generated by hakoniwa-ros2pdu.
    """

    data: List[float]

    def __init__(self):
        self.data = []

    def __str__(self):
        return f"DisturbanceUserCustom(" + ", ".join([
            f"data={self.data}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'data'
        field_val = self.data
        if isinstance(field_val, bytearray):
            d['data'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['data'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['data'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['data'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'data'
        if 'data' in d:
            field_type = cls.__annotations__.get('data')
            value = d['data']
            
            if field_type is bytearray:
                obj.data = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.data = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.data = value
            elif hasattr(field_type, 'from_dict'):
                obj.data = field_type.from_dict(value)
            else:
                obj.data = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
