from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Time:
    """
    ROS message: builtin_interfaces/Time
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.sec: int = 0
        self.nanosec: int = 0

    def __str__(self):
        return f"Time(" + ", ".join([
            f"sec={self.sec}"
            f"nanosec={self.nanosec}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
