from typing import List

# dependencies for the generated Python class

from ..builtin_interfaces.pdu_pytype_Time import Time


# class definition for the ROS message
class Header:
    """
    ROS message: std_msgs/Header
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.stamp: Time = Time()
        self.frame_id: str = ""

    def __str__(self):
        return f"Header(" + ", ".join([
            f"stamp={self.stamp}"
            f"frame_id={self.frame_id}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
