from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Char:
    """
    ROS message: std_msgs/Char
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.data: str = 0

    def __str__(self):
        return f"Char(" + ", ".join([
            f"data={self.data}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
