from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class MultiArrayDimension:
    """
    ROS message: std_msgs/MultiArrayDimension
    Generated by hakoniwa-ros2pdu.
    """

    label: str
    size: int
    stride: int

    def __init__(self):
        self.label = ""
        self.size = 0
        self.stride = 0

    def __str__(self):
        return f"MultiArrayDimension(" + ", ".join([
            f"label={self.label}"
            f"size={self.size}"
            f"stride={self.stride}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'label'
        field_val = self.label
        if isinstance(field_val, bytearray):
            d['label'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['label'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['label'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['label'] = field_val
        # handle field 'size'
        field_val = self.size
        if isinstance(field_val, bytearray):
            d['size'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['size'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['size'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['size'] = field_val
        # handle field 'stride'
        field_val = self.stride
        if isinstance(field_val, bytearray):
            d['stride'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['stride'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['stride'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['stride'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'label'
        if 'label' in d:
            field_type = cls.__annotations__.get('label')
            value = d['label']
            
            if field_type is bytearray:
                obj.label = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.label = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.label = value
            elif hasattr(field_type, 'from_dict'):
                obj.label = field_type.from_dict(value)
            else:
                obj.label = value
        # handle field 'size'
        if 'size' in d:
            field_type = cls.__annotations__.get('size')
            value = d['size']
            
            if field_type is bytearray:
                obj.size = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.size = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.size = value
            elif hasattr(field_type, 'from_dict'):
                obj.size = field_type.from_dict(value)
            else:
                obj.size = value
        # handle field 'stride'
        if 'stride' in d:
            field_type = cls.__annotations__.get('stride')
            value = d['stride']
            
            if field_type is bytearray:
                obj.stride = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.stride = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.stride = value
            elif hasattr(field_type, 'from_dict'):
                obj.stride = field_type.from_dict(value)
            else:
                obj.stride = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
