from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class MultiArrayDimension:
    """
    ROS message: std_msgs/MultiArrayDimension
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.label: str = ""
        self.size: int = 0
        self.stride: int = 0

    def __str__(self):
        return f"MultiArrayDimension(" + ", ".join([
            f"label={self.label}"
            f"size={self.size}"
            f"stride={self.stride}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
