from typing import List

# dependencies for the generated Python class

from ..std_msgs.pdu_pytype_MultiArrayDimension import MultiArrayDimension

from ..std_msgs.pdu_pytype_MultiArrayLayout import MultiArrayLayout


# class definition for the ROS message
class Float32MultiArray:
    """
    ROS message: std_msgs/Float32MultiArray
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.layout: MultiArrayLayout = MultiArrayLayout()
        self.data: List[float] = []

    def __str__(self):
        return f"Float32MultiArray(" + ", ".join([
            f"layout={self.layout}"
            f"data={self.data}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
