from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Int64:
    """
    ROS message: std_msgs/Int64
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.data: int = 0

    def __str__(self):
        return f"Int64(" + ", ".join([
            f"data={self.data}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
