from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Byte:
    """
    ROS message: std_msgs/Byte
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.data: int = 0

    def __str__(self):
        return f"Byte(" + ", ".join([
            f"data={self.data}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
