from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class Bool:
    """
    ROS message: std_msgs/Bool
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.data: bool = False

    def __str__(self):
        return f"Bool(" + ", ".join([
            f"data={self.data}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
