from typing import List

# dependencies for the generated Python class

from ..std_msgs.pdu_pytype_MultiArrayDimension import MultiArrayDimension


# class definition for the ROS message
class MultiArrayLayout:
    """
    ROS message: std_msgs/MultiArrayLayout
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.dim: List[MultiArrayDimension] = []
        self.data_offset: int = 0

    def __str__(self):
        return f"MultiArrayLayout(" + ", ".join([
            f"dim={self.dim}"
            f"data_offset={self.data_offset}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
