

/**
 * ROS message: drone_srv_msgs/MagnetGrabRequest
 * Generated by hakoniwa-ros2pdu.
 */
export class MagnetGrabRequest {
/** @type { string } */
    drone_name;
/** @type { boolean } */
    grab_on;
/** @type { number } */
    timeout_sec;


    constructor() {
        this.drone_name = "";
        this.grab_on = false;
        this.timeout_sec = 0.0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'drone_name'
            const field_val = this.drone_name;
            if (typeof field_val?.toDict === 'function') {
                d['drone_name'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['drone_name'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['drone_name'] = field_val;
            }
        }
        {
            // handle field 'grab_on'
            const field_val = this.grab_on;
            if (typeof field_val?.toDict === 'function') {
                d['grab_on'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['grab_on'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['grab_on'] = field_val;
            }
        }
        {
            // handle field 'timeout_sec'
            const field_val = this.timeout_sec;
            if (typeof field_val?.toDict === 'function') {
                d['timeout_sec'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['timeout_sec'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['timeout_sec'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { MagnetGrabRequest }
     */
    static fromDict(d) {
        const obj = new MagnetGrabRequest();
        if (d.hasOwnProperty('drone_name')) {
            obj.drone_name = d.drone_name;
        }
        if (d.hasOwnProperty('grab_on')) {
            obj.grab_on = d.grab_on;
        }
        if (d.hasOwnProperty('timeout_sec')) {
            obj.timeout_sec = d.timeout_sec;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { MagnetGrabRequest }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
