

/**
 * ROS message: drone_srv_msgs/CameraCaptureImageRequest
 * Generated by hakoniwa-ros2pdu.
 */
export class CameraCaptureImageRequest {
/** @type { string } */
    drone_name;
/** @type { string } */
    image_type;


    constructor() {
        this.drone_name = "";
        this.image_type = "";
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'drone_name'
            const field_val = this.drone_name;
            if (typeof field_val?.toDict === 'function') {
                d['drone_name'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['drone_name'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['drone_name'] = field_val;
            }
        }
        {
            // handle field 'image_type'
            const field_val = this.image_type;
            if (typeof field_val?.toDict === 'function') {
                d['image_type'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['image_type'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['image_type'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { CameraCaptureImageRequest }
     */
    static fromDict(d) {
        const obj = new CameraCaptureImageRequest();
        if (d.hasOwnProperty('drone_name')) {
            obj.drone_name = d.drone_name;
        }
        if (d.hasOwnProperty('image_type')) {
            obj.image_type = d.image_type;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { CameraCaptureImageRequest }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
