

/**
 * ROS message: drone_srv_msgs/CameraSetTiltRequest
 * Generated by hakoniwa-ros2pdu.
 */
export class CameraSetTiltRequest {
/** @type { string } */
    drone_name;
/** @type { number } */
    tilt_angle_deg;


    constructor() {
        this.drone_name = "";
        this.tilt_angle_deg = 0.0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'drone_name'
            const field_val = this.drone_name;
            if (typeof field_val?.toDict === 'function') {
                d['drone_name'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['drone_name'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['drone_name'] = field_val;
            }
        }
        {
            // handle field 'tilt_angle_deg'
            const field_val = this.tilt_angle_deg;
            if (typeof field_val?.toDict === 'function') {
                d['tilt_angle_deg'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['tilt_angle_deg'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['tilt_angle_deg'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { CameraSetTiltRequest }
     */
    static fromDict(d) {
        const obj = new CameraSetTiltRequest();
        if (d.hasOwnProperty('drone_name')) {
            obj.drone_name = d.drone_name;
        }
        if (d.hasOwnProperty('tilt_angle_deg')) {
            obj.tilt_angle_deg = d.tilt_angle_deg;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { CameraSetTiltRequest }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
