from typing import List

# dependencies for the generated Python class

from ..std_msgs.pdu_pytype_Header import Header

from ..geometry_msgs.pdu_pytype_Point import Point

from ..geometry_msgs.pdu_pytype_Pose import Pose

from ..geometry_msgs.pdu_pytype_PoseWithCovariance import PoseWithCovariance

from ..geometry_msgs.pdu_pytype_Quaternion import Quaternion

from ..builtin_interfaces.pdu_pytype_Time import Time

from ..geometry_msgs.pdu_pytype_Twist import Twist

from ..geometry_msgs.pdu_pytype_TwistWithCovariance import TwistWithCovariance

from ..geometry_msgs.pdu_pytype_Vector3 import Vector3


# class definition for the ROS message
class Odometry:
    """
    ROS message: nav_msgs/Odometry
    Generated by hakoniwa-ros2pdu.
    """
    
    def __init__(self):
        self.header: Header = Header()
        self.child_frame_id: str = ""
        self.pose: PoseWithCovariance = PoseWithCovariance()
        self.twist: TwistWithCovariance = TwistWithCovariance()

    def __str__(self):
        return f"Odometry(" + ", ".join([
            f"header={self.header}"
            f"child_frame_id={self.child_frame_id}"
            f"pose={self.pose}"
            f"twist={self.twist}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()
